//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Videoteka.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Videoteka.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Avengers,4
        ///Avengers: Age of Ultron,4
        ///Avengers: Infinity War,4
        ///Avengers: Endgame,4
        ///The Goonies,4
        ///Lord of the rings: Fellowship of the Ring,4
        ///Lord of the rings: Two towers,4
        ///Lord of the rings: Return of the King,4.
        /// </summary>
        internal static string BazaFilmova {
            get {
                return ResourceManager.GetString("BazaFilmova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Avengers,4
        ///Avengers: Age of Ultron,4
        ///Avengers: Infinity War,4
        ///Avengers: Endgame,4
        ///The Goonies,4
        ///Lord of the rings: Fellowship of the Ring,4
        ///Lord of the rings: Two towers,4
        ///Lord of the rings: Return of the King,4.
        /// </summary>
        internal static string Filmovi {
            get {
                return ResourceManager.GetString("Filmovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Iznajmljivanja {
            get {
                return ResourceManager.GetString("Iznajmljivanja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pero Perić, Matije Gupca 153, 32236, Ilok
        ///Jovan Jovanović, Grada Vukovara 17, 32236, Mohovo
        ///Vinko Grbeš, Vukovarska 4, 32234, Šarengrad.
        /// </summary>
        internal static string Korisnici {
            get {
                return ResourceManager.GetString("Korisnici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        internal static string KorisničkoIme {
            get {
                return ResourceManager.GetString("KorisničkoIme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        internal static string Lozinke {
            get {
                return ResourceManager.GetString("Lozinke", resourceCulture);
            }
        }
    }
}
